[package]
name = "libc-print"
version = "0.3.0"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2021"
description = "println! and eprintln! macros on libc without stdlib"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/rust-libc-print"
readme = "README.md"

[lib]
name = "libc_print"

[dependencies]

[target.'cfg(not(windows))'.dependencies]
libc = { version = "0.2.186", default-features = false }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(nostartfiles)'
] }
