name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --lib --verbose
    - name: Run example with RUSTFLAGS=-nostartfiles (linux)
      if: matrix.os == 'ubuntu-latest'
      run: RUSTFLAGS="-C link-arg=-nostartfiles" cargo run --example writeln --target x86_64-unknown-linux-gnu
    - name: Run example with RUSTFLAGS=-nostartfiles (mac)
      if: matrix.os == 'macOS-latest'
      run: RUSTFLAGS="-C link-args=-e __start -static -nostartfiles" cargo run --example writeln --target x86_64-apple-darwin
    - name: Run example with RUSTFLAGS=-nostartfiles (windows)
      if: matrix.os == 'windows-latest'
      run: RUSTFLAGS="-C link-args=/ENTRY:_start /SUBSYSTEM:console" cargo run --example writeln --target x86_64-pc-windows-msvc
